openapi: 3.0.1
info:
  title: Starbucks API Example
  description: Starbucks API
  version: 1.0.0
servers:
- url: /api
paths:
  /coffee:
    get:
      tags:
      - Coffee
      summary: The coffee data structure for our server application
      description: Read the list of coffee drinks
      operationId: coffee.read
      responses:
        200:
          description: Successful read coffee list operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    coffee_name:
                      type: string
                    milk:
                      type: string
                    timestamp:
                      type: string
  /coffee/{coffee_name}:
    get:
      tags:
      - Coffee
      summary: Read one drink from the coffee object
      description: Read one drink from the coffee object
      operationId: coffee.read_one
      parameters:
      - name: coffee_name
        in: path
        description: Name of coffee get from the list
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successfully read coffee from coffee list
          content:
            application/json:
              schema:
                type: object
components: {}